services:
  main-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main-app
    ports:
      - "8000:8000"
    command: "sh entrypoint.sh"
    env_file:
      - ./.env
    volumes:
      - ..:/app/